export const projectsData = [
    {
      id: 1,
      image: "/src/assets/Fivanimg.svg",
      imageAlt: "Fivani dashboard on laptop and mobile devices",
      imageBackgroundColor: "#5046e5",
      smallHeading: "Saas Platform",
      bigHeading: "Fivani",
      subHeading: "Web, Dashboard, and Mobile Design",
      description:
        "Empowering freelancers to manage contracts, projects, and payments seamlessly, all in one secure platform",
      primaryButtonText: "View Case-Study",
      secondaryButtonText: "Check Website Link",
      primaryButtonLink: "/case-study/fivani",
      secondaryButtonLink: "https://fivani.com",
      imagePosition: "left",
    },
    {
      id: 2,
      image: "/src/assets/BuddyApp.svg",
      imageAlt: "BuddyApp mobile interface showing travel connections",
      imageBackgroundColor: "#c084fc",
      smallHeading: "Hospitality",
      bigHeading: "BuddyApp",
      subHeading: "Mobile App",
      description: "Connecting solo travelers for safer, more enjoyable journeys filled with shared experiences",
      primaryButtonText: "View Case-Study",
      secondaryButtonText: "Check Figma Link",
      primaryButtonLink: "/case-study/buddyapp",
      secondaryButtonLink: "https://figma.com/buddyapp",
       imagePosition: "left",
    },
    {
      id: 3,
      image: "/src/assets/Zorft.svg",
      imageAlt: "Zorfts Technologies website on laptop and mobile",
      imageBackgroundColor: "#3b82f6",
      smallHeading: "Portfolio Website",
      bigHeading: "Zorfts Technologies",
      subHeading: "Web and Mobile Design",
      description: "Bringing fresh produce and essentials directly to your doorstep with convenience and reliability",
      primaryButtonText: "View Case-Study",
      secondaryButtonText: "Check Website Link",
      primaryButtonLink: "/case-study/zorfts",
      secondaryButtonLink: "https://zorfts.com",
      imagePosition: "left",
    },
    {
      id: 4,
      image: "/src/assets/HomeVolt.svg",
      imageAlt: "HomeVolt property and energy platform interface",
      imageBackgroundColor: "#06b6d4",
      smallHeading: "Lifestyle and Home",
      bigHeading: "HomeVolt",
      subHeading: "Web, Dashboard and Mobile Design",
      description: "Simplifying Property Rentals, Sales, and Renewable Energy Solutions",
      primaryButtonText: "View Case-Study",
      secondaryButtonText: "Check Website Link",
      primaryButtonLink: "/case-study/homevolt",
      secondaryButtonLink: "https://homevolt.com",
       imagePosition: "left",
    },
  ]
  